// NOTE: This file is generated by Uniwind's Metro integration and is committed
// so repository-wide typecheck does not depend on running Metro first.

/// <reference types="uniwind/types" />

declare module 'uniwind' {
  export interface UniwindConfig {
    themes: readonly ['light', 'dark'];
  }
}

export {};
