import { fireEvent, render } from '@testing-library/react-native';
import * as React from 'react';
import {
  Accordion, AccordionContent, AccordionItem, AccordionTrigger, AlertBanner, AppHeader,
  BottomActionBar, Button, Checkbox, Collapsible, CollapsibleContent, CollapsibleTrigger,
  Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogTitle, DialogTrigger,
  Field, Input, ListItem, MetadataRow, OTPInput, PasswordInput, Progress, Radio, RadioGroup,
  Screen, SearchInput, Section, Switch, Tabs, TabsContent, TabsList, TabsTrigger, Text,
} from '@beeui/ui';

describe('BeeUI component contracts', () => {
  it('exposes an accessible button and forwards presses', () => { const onPress = jest.fn(); const screen = render(<Button onPress={onPress}>Save changes</Button>); const button = screen.getByRole('button', { name: 'Save changes' }); expect(button.props.accessibilityState).toEqual({ disabled: false, busy: false }); fireEvent.press(button); expect(onPress).toHaveBeenCalledTimes(1); });
  it('preserves caller accessibility state while enforcing loading semantics', () => { const onPress = jest.fn(); const screen = render(<Button accessibilityState={{ selected: true }} loading onPress={onPress}>Save</Button>); const button = screen.getByRole('button', { name: 'Save' }); expect(button.props.accessibilityState).toEqual({ selected: true, disabled: true, busy: true }); fireEvent.press(button); expect(onPress).not.toHaveBeenCalled(); });
  it('keeps disabled inputs non-editable while preserving accessibility state', () => { const screen = render(<Input accessibilityLabel="Email" accessibilityState={{ selected: true }} disabled placeholder="Email" />); const input = screen.getByLabelText('Email'); expect(input.props.editable).toBe(false); expect(input.props.accessibilityState).toEqual({ selected: true, disabled: true }); });
  it('propagates Field label, error, and state into Input', () => { const screen = render(<Field error="Enter a valid email" invalid label="Email"><Input /></Field>); const input = screen.getByLabelText('Email'); expect(input.props.accessibilityHint).toBe('Enter a valid email'); expect(input.props.accessibilityState.disabled).toBe(false); expect(screen.getByText('Enter a valid email')).toBeTruthy(); });
  it('exposes checkbox state and requests controlled changes', () => { const onCheckedChange = jest.fn(); const screen = render(<Checkbox checked={false} label="Accept terms" onCheckedChange={onCheckedChange} />); const checkbox = screen.getByRole('checkbox', { name: 'Accept terms' }); expect(checkbox.props.accessibilityState).toEqual({ checked: false, disabled: false }); fireEvent.press(checkbox); expect(onCheckedChange).toHaveBeenCalledWith(true); });
  it('maps switch value to its accessibility state', () => { const screen = render(<Switch accessibilityLabel="Notifications" value />); const toggle = screen.getByRole('switch', { name: 'Notifications' }); expect(toggle.props.accessibilityState).toEqual({ checked: true, disabled: false }); });
  it('coordinates radio values through RadioGroup', () => { const onValueChange = jest.fn(); const screen = render(<RadioGroup accessibilityLabel="Plan" onValueChange={onValueChange} value="starter"><Radio label="Starter plan" value="starter" /><Radio label="Pro plan" value="pro" /></RadioGroup>); const group = screen.getByLabelText('Plan'); const starter = screen.getByRole('radio', { name: 'Starter plan' }); const pro = screen.getByRole('radio', { name: 'Pro plan' }); expect(group.props.accessibilityRole).toBe('radiogroup'); expect(starter.props.accessibilityState.checked).toBe(true); expect(pro.props.accessibilityState.checked).toBe(false); fireEvent.press(pro); expect(onValueChange).toHaveBeenCalledWith('pro'); });
  it('coordinates tab selection and only mounts active content', () => { const onValueChange = jest.fn(); const screen = render(<Tabs onValueChange={onValueChange} value="overview"><TabsList><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="details">Details</TabsTrigger></TabsList><TabsContent value="overview"><Text>Overview content</Text></TabsContent><TabsContent value="details"><Text>Details content</Text></TabsContent></Tabs>); const overview = screen.getByRole('tab', { name: 'Overview' }); const details = screen.getByRole('tab', { name: 'Details' }); expect(overview.props.accessibilityState.selected).toBe(true); expect(details.props.accessibilityState.selected).toBe(false); expect(screen.getByText('Overview content')).toBeTruthy(); expect(screen.queryByText('Details content')).toBeNull(); fireEvent.press(details); expect(onValueChange).toHaveBeenCalledWith('details'); });
  it('clamps progress values for accessibility', () => { const screen = render(<Progress accessibilityLabel="Upload" max={100} value={140} />); const progress = screen.getByLabelText('Upload'); expect(progress.props.accessibilityRole).toBe('progressbar'); expect(progress.props.accessibilityValue).toEqual({ min: 0, max: 100, now: 100 }); });
  it('toggles uncontrolled Collapsible content and exposes expanded state', () => { const screen = render(<Collapsible><CollapsibleTrigger>Advanced</CollapsibleTrigger><CollapsibleContent><Text>Advanced content</Text></CollapsibleContent></Collapsible>); const trigger = screen.getByRole('button', { name: 'Advanced' }); expect(trigger.props.accessibilityState.expanded).toBe(false); expect(screen.queryByText('Advanced content')).toBeNull(); fireEvent.press(trigger); expect(screen.getByText('Advanced content')).toBeTruthy(); });
  it('coordinates single Accordion state', () => { const screen = render(<Accordion defaultValue="account"><AccordionItem value="account"><AccordionTrigger>Account</AccordionTrigger><AccordionContent><Text>Account content</Text></AccordionContent></AccordionItem><AccordionItem value="billing"><AccordionTrigger>Billing</AccordionTrigger><AccordionContent><Text>Billing content</Text></AccordionContent></AccordionItem></Accordion>); expect(screen.getByText('Account content')).toBeTruthy(); expect(screen.queryByText('Billing content')).toBeNull(); fireEvent.press(screen.getByRole('button', { name: 'Billing' })); expect(screen.queryByText('Account content')).toBeNull(); expect(screen.getByText('Billing content')).toBeTruthy(); });
  it('forwards ListItem presses with inferred button labeling', () => { const onPress = jest.fn(); const screen = render(<ListItem description="Account preferences" onPress={onPress} title="Settings" />); fireEvent.press(screen.getByRole('button', { name: 'Settings' })); expect(onPress).toHaveBeenCalledTimes(1); });
  it('configures SearchInput and forwards submitted search text', () => { const onSearch = jest.fn(); const screen = render(<SearchInput accessibilityLabel="Search" onSearch={onSearch} />); const input = screen.getByLabelText('Search'); expect(input.props.inputMode).toBe('search'); expect(input.props.returnKeyType).toBe('search'); fireEvent(input, 'submitEditing', { nativeEvent: { text: 'bee ui' } }); expect(onSearch).toHaveBeenCalledWith('bee ui'); });
  it('toggles PasswordInput visibility', () => { const screen = render(<PasswordInput accessibilityLabel="Password" />); expect(screen.getByLabelText('Password').props.secureTextEntry).toBe(true); fireEvent.press(screen.getByRole('button', { name: 'Show password' })); expect(screen.getByLabelText('Password').props.secureTextEntry).toBe(false); expect(screen.getByRole('button', { name: 'Hide password' })).toBeTruthy(); });
  it('normalizes numeric OTP input and emits completion once length is reached', () => { const onValueChange = jest.fn(); const onComplete = jest.fn(); const screen = render(<OTPInput accessibilityLabel="Verification code" length={4} onComplete={onComplete} onValueChange={onValueChange} />); fireEvent.changeText(screen.getByLabelText('Verification code'), '12a34'); expect(onValueChange).toHaveBeenCalledWith('1234'); expect(onComplete).toHaveBeenCalledWith('1234'); });
  it('renders application chrome without owning navigation behavior', () => { const screen = render(<><AppHeader description="Workspace" title="BeeUI" trailing={<Button>Help</Button>} /><BottomActionBar><Button>Save</Button></BottomActionBar></>); expect(screen.getByText('BeeUI')).toBeTruthy(); expect(screen.getByText('Workspace')).toBeTruthy(); expect(screen.getByRole('button', { name: 'Save' })).toBeTruthy(); });
  it('renders screen and section composition without safe-area or navigation ownership', () => { const screen = render(<Screen><Section action={<Button>Edit</Button>} description="Account details" title="Profile"><MetadataRow label="Status" value="Active" /></Section></Screen>); expect(screen.getByText('Profile')).toBeTruthy(); expect(screen.getByText('Account details')).toBeTruthy(); expect(screen.getByText('Status')).toBeTruthy(); expect(screen.getByText('Active')).toBeTruthy(); expect(screen.getByRole('button', { name: 'Edit' })).toBeTruthy(); });
  it('maps AlertBanner variant content to a polite live region by default', () => { const screen = render(<AlertBanner description="Connection restored." testID="status-banner" title="Online" variant="success" />); expect(screen.getByText('Online')).toBeTruthy(); expect(screen.getByText('Connection restored.')).toBeTruthy(); expect(screen.getByTestId('status-banner').props.accessibilityLiveRegion).toBe('polite'); });
  it('opens and closes an uncontrolled Dialog through its trigger and close button', () => { const screen = render(<Dialog><DialogTrigger>Open dialog</DialogTrigger><DialogContent testID="dialog-content"><DialogTitle>Confirm change</DialogTitle><DialogDescription>This action can be reviewed before saving.</DialogDescription><DialogFooter><DialogClose variant="outline">Cancel</DialogClose><Button>Confirm</Button></DialogFooter></DialogContent></Dialog>); expect(screen.queryByTestId('dialog-content')).toBeNull(); fireEvent.press(screen.getByRole('button', { name: 'Open dialog' })); const content = screen.getByTestId('dialog-content'); expect(content.props.role).toBe('dialog'); expect(content.props.accessibilityViewIsModal).toBe(true); expect(screen.getByText('Confirm change')).toBeTruthy(); fireEvent.press(screen.getByRole('button', { name: 'Cancel' })); expect(screen.queryByTestId('dialog-content')).toBeNull(); });
  it('dismisses Dialog from its semantic backdrop and reports state changes', () => { const onOpenChange = jest.fn(); const screen = render(<Dialog defaultOpen onOpenChange={onOpenChange}><DialogContent overlayTestID="dialog-overlay" testID="dialog-content"><DialogTitle>Preferences</DialogTitle></DialogContent></Dialog>); fireEvent.press(screen.getByTestId('dialog-overlay')); expect(onOpenChange).toHaveBeenCalledWith(false); expect(screen.queryByTestId('dialog-content')).toBeNull(); });
});
