// GENERATED by scripts/generate-production-pattern-usage.mjs — do not edit by hand.
// Run `pnpm showcase:production-usage:generate` after changing pattern screen composition.
//
// Maps a public component family to the production pattern screens that actually import one of
// its public symbols. #472 section 2 requires the `production` coverage class to be a real
// mapping to a pattern where the component is used; deriving it from imports keeps that link
// honest instead of hand-asserted.

export const PRODUCTION_PATTERN_USAGE: Readonly<Record<string, readonly string[]>> = {
  'alert-banner': ['change-password', 'checkout', 'edit-profile', 'profile-setup', 'sign-up'],
  'avatar': ['edit-profile', 'notifications', 'post-detail', 'profile-setup', 'social-feed', 'user-profile'],
  'badge': ['invoice-detail', 'notifications', 'order-detail', 'orders', 'payment-methods', 'privacy-security', 'product-detail', 'product-feed', 'settings-home', 'subscription', 'transaction-detail'],
  'box': ['appearance', 'change-password', 'edit-profile', 'password-updated', 'product-feed', 'product-search', 'profile', 'welcome'],
  'button': ['cart', 'change-password', 'checkout', 'dashboard-overview', 'edit-profile', 'forgot-password', 'interests-onboarding', 'invoice-detail', 'notifications', 'order-detail', 'orders', 'password-updated', 'payment-methods', 'post-detail', 'product-detail', 'product-feed', 'product-search', 'profile-setup', 'reset-password', 'sign-in', 'sign-up', 'social-feed', 'subscription', 'transaction-detail', 'transactions', 'user-profile', 'verify-code', 'wallet', 'welcome'],
  'card': ['analytics', 'cart', 'dashboard-overview', 'forgot-password', 'interests-onboarding', 'invoice-detail', 'notifications', 'order-detail', 'orders', 'password-updated', 'payment-methods', 'post-detail', 'product-detail', 'product-feed', 'product-search', 'profile-setup', 'reset-password', 'sign-in', 'sign-up', 'social-feed', 'subscription', 'transaction-detail', 'transactions', 'user-profile', 'verify-code', 'wallet', 'welcome'],
  'checkbox': ['checkout', 'sign-up'],
  'chip': ['interests-onboarding', 'product-detail', 'product-feed', 'product-search'],
  'description-list': ['invoice-detail', 'transaction-detail'],
  'field': ['change-password', 'edit-profile', 'forgot-password', 'profile-setup', 'reset-password', 'sign-in', 'sign-up', 'verify-code'],
  'input': ['edit-profile', 'forgot-password', 'post-detail', 'profile-setup', 'sign-in', 'sign-up'],
  'link': ['forgot-password', 'interests-onboarding', 'profile-setup', 'sign-in', 'sign-up', 'verify-code'],
  'list-group': ['account', 'notification-settings', 'privacy-security', 'profile', 'settings-home'],
  'list-item': ['account', 'privacy-security', 'profile', 'settings-home'],
  'otp-input': ['verify-code'],
  'password-input': ['change-password', 'reset-password', 'sign-in', 'sign-up'],
  'progress': ['analytics', 'subscription'],
  'radio': ['checkout'],
  'search-input': ['messages', 'product-feed', 'product-search', 'transactions'],
  'segmented-control': ['appearance', 'orders'],
  'separator': ['account', 'cart', 'checkout', 'notification-settings', 'order-detail', 'post-detail', 'privacy-security', 'product-detail', 'profile', 'settings-home', 'user-profile'],
  'skeleton': ['dashboard-overview', 'product-feed', 'product-search', 'social-feed'],
  'stack': ['account', 'analytics', 'appearance', 'cart', 'change-password', 'checkout', 'dashboard-overview', 'edit-profile', 'forgot-password', 'interests-onboarding', 'invoice-detail', 'messages', 'notifications', 'order-detail', 'orders', 'password-updated', 'payment-methods', 'post-detail', 'product-detail', 'product-feed', 'product-search', 'profile', 'profile-setup', 'reset-password', 'sign-in', 'sign-up', 'social-feed', 'subscription', 'transaction-detail', 'transactions', 'user-profile', 'verify-code', 'wallet', 'welcome'],
  'stat': ['analytics'],
  'state-message': ['analytics', 'cart', 'dashboard-overview', 'messages', 'notifications', 'orders', 'product-search', 'social-feed', 'transactions', 'user-profile', 'wallet'],
  'switch': ['settings-home'],
  'tabs': ['analytics', 'transactions'],
  'text': ['account', 'analytics', 'appearance', 'cart', 'change-password', 'checkout', 'dashboard-overview', 'interests-onboarding', 'invoice-detail', 'messages', 'notifications', 'order-detail', 'orders', 'password-updated', 'payment-methods', 'post-detail', 'product-detail', 'product-feed', 'product-search', 'profile', 'sign-in', 'sign-up', 'social-feed', 'subscription', 'transaction-detail', 'transactions', 'user-profile', 'verify-code', 'wallet', 'welcome'],
  'textarea': ['edit-profile', 'profile-setup'],
  'timeline': ['order-detail'],
};
